/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_rust_RustNative */

#ifndef _Included_com_jni_rust_RustNative
#define _Included_com_jni_rust_RustNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_rust_RustNative
 * Method:    getEncryptStringFromRust
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_rust_RustNative_getEncryptStringFromRust
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jni_rust_RustNative
 * Method:    getDecryptStringFromRust
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_rust_RustNative_getDecryptStringFromRust
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
